# .github/workflows/python-publish.yml
name: Publish Python 🐍 package 📦 to TestPyPI & PyPI

on:
  push:
    branches: [master]          # build + TestPyPI para cada commit na master
    tags:     ['v*']          # build + PyPI quando a ref for tag vX.Y.Z
  workflow_dispatch: {}       # botão “Run workflow” para testes manuais

permissions:
  contents: read              # checkout
  id-token: write             # OIDC para trusted publishing

jobs:
  build:
    name: Build distributions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"   

      - name: Install build backend
        run: python -m pip install --upgrade build

      - name: Build wheel + sdist
        run: python -m build --sdist --wheel --out dist

      - name: Upload dists as artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-package-dists
          path: dist/

  publish-testpypi:
    name: Publish to TestPyPI
    needs: build
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/project/softrag/   

    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: python-package-dists
          path: dist/

      - name: Upload to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: dist/
          verbose: true

  publish-pypi:
    name: Publish to PyPI
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/project/softrag/      

    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: python-package-dists
          path: dist/

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
