# .github/workflows/publish.yml
name: Upload Python Package (uv)

on:
  release:
    types: [published]

permissions:
  contents: read         # checkout
  id-token: write        # needed for Trusted Publishing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"   # pick explicit minor for reproducibility

      - name: Build release distributions
        run: |
          uv build --sdist --wheel --out dist

      - uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  publish:
    needs: build
    runs-on: ubuntu-latest
    environment: pypi         # define in repo ➜ allows manual approvals etc.

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          verbose: true         # optional, shows detailed upload log
